name: Housing
version: '${project.version}'
main: net.jadedmc.housing.HousingPlugin
api-version: 1.13

commands:
  savetemplate:
    description: Saves a template.
  createhouse:
    description: Creates a house
  loadhouse:
    description: Load a house.
  menu:
    description: Opens the house menu.
  setname:
    description: Set the name of a house.
  transfer:
    description: Transfer a house to a new owner.
  leave:
    description: Leave a house.
    aliases: [l]
  visit:
    description: Visit another player's house.
  houseuuid:
    description: Find the current house UUID.