name: Housing
version: '${project.version}'
main: net.jadedmc.housing.HousingPlugin
api-version: 1.13

commands:
  savetemplate:
    description: Saves a template.
  createhouse:
    description: Creates a house
  loadhouse:
    description: Load a house.
  menu:
    description: Opens the house menu.